messages:
  enabled: "§aCoordinates enabled. use /xyz off too disable coords"
  disabled: "§cCoordinates disabled. use /xyz on too enable coords"
  usage: "§eUsage: /xyz <on|off>"

coords-format: "§7XYZ: §f{x} §7| §f{y} §7| §f{z}"
update-interval: 20
